CC=gcc
CFLAGS=-Wall -Wextra -Werror 
NAME=rush-02
OBJECTS=*.o
FILES=functions.c magnitude.c translate.c file_to_struct.c main.c

all:
	$(CC) $(CFLAGS) $(FILES) -o $(NAME)
 
clean:
	rm $(NAME)
fclean: 
	rm $(OBJECTS)
